---
language: go
go:
- 1.12.x

install:
- curl --silent --location https://goo.gl/g1CpPX | bash -s v1.0.7

script:
- GO111MODULE=on go mod download
- GO111MODULE=on go mod verify
- GO111MODULE=on ginkgo -r -nodes 4 -randomizeAllSpecs -randomizeSuites -race -trace
